let currentLang='en';const langPack={tr:{searchPlaceholder:"Balık adı ara...",noFish:"Eşleşen balık bulunamadı...",listed:"Listelenen:",fishCount:"Balık",allFish:" Tüm Balıklar",resetAll:"Filtreleri Sıfırla",tabArea:" Bölgeler",tabBait:" Yemler",tabStars:" Yıldızlar (Nadirlik)",btnAllAreas:"Tüm Bölgeler",btnAllBaits:"Tüm Yemler",btnAllStars:"Tüm Zorluklar",thImage:"GÖRSEL",thFish:"BALIK",thArea:"BÖLGE",thBait:"YEM",thSeason:"MEVSİM",thTime:"SAAT",thRecord:"DÜNYA REKORU",thPrice:"MAKS FİYAT"},en:{searchPlaceholder:"Search fish name...",noFish:"No matching fish found...",listed:"Listed:",fishCount:"Fish",allFish:" All Fish",resetAll:"Reset All",tabArea:" Area Fish",tabBait:" Bait Fish",tabStars:" Stars (Rarity)",btnAllAreas:"All Areas",btnAllBaits:"All Baits",btnAllStars:"All Difficulties",thImage:"IMAGE",thFish:"FISH",thArea:"AREA",thBait:"BAIT",thSeason:"SEASON",thTime:"TIME",thRecord:"WORLD RECORD",thPrice:"MAX PRICE"}};let selectedArea="All";let selectedBait="All";let selectedStars="All";let activeOpenedPanel=null;let lastActiveTab="area";const tableBody=document.getElementById("fishTableBody");const searchInput=document.getElementById("fishSearch");let searchTimeout=null;let globalFiltrelenmisBaliklar=[];let gosterilenBalikSayisi=0;const SAYFA_BASINA_BALIK=30;function toggleLanguage(){currentLang=currentLang==='en'?'tr':'en';const flagEl=document.getElementById("lang-flag");if(flagEl)flagEl.innerText=currentLang==='en'?'🇹🇷':'🇬🇧';const updateTabText=(id,iconClass,text)=>{const el=document.querySelector(`#${id} .tab-title`);if(el)el.innerHTML=`<i class="${iconClass}"></i>${text}`};updateTabText("lbl-all-fish","fa-solid fa-fish-fins",langPack[currentLang].allFish);updateTabText("tab-area","fa-solid fa-map-location-dot",langPack[currentLang].tabArea);updateTabText("tab-bait","fa-solid fa-shrimp",langPack[currentLang].tabBait);updateTabText("tab-stars","fa-solid fa-star",langPack[currentLang].tabStars);const safeTranslate=(id,text)=>{const el=document.getElementById(id);if(el){if(el.tagName==='INPUT')el.placeholder=text;else el.innerText=text}};safeTranslate("lbl-reset-all",langPack[currentLang].resetAll);safeTranslate("fishSearch",langPack[currentLang].searchPlaceholder);safeTranslate("lbl-listed",langPack[currentLang].listed);safeTranslate("lbl-fish-count",langPack[currentLang].fishCount);safeTranslate("btn-all-areas",langPack[currentLang].btnAllAreas);safeTranslate("btn-all-baits",langPack[currentLang].btnAllBaits);safeTranslate("btn-all-stars",langPack[currentLang].btnAllStars);const alertCell=document.querySelector("#no-fish-alert-row td");if(alertCell)alertCell.innerText=langPack[currentLang].noFish;buildTableStructure();updateTable();updateTabSubtitles()}
function updateTabSubtitles(){const subArea=document.getElementById("sub-area");const subBait=document.getElementById("sub-bait");const subStars=document.getElementById("sub-stars");if(subArea){if(selectedArea==="All"){subArea.innerText=currentLang==='tr'?"Tüm Bölgeler":"All Areas"}else if(typeof selectedSubArea!=="undefined"&&selectedSubArea!=="All"){subArea.innerText=selectedSubArea}else{subArea.innerText=selectedArea}}
if(subBait)subBait.innerText=selectedBait==="All"?(currentLang==='tr'?"Tüm Yemler":"All Baits"):selectedBait;if(subStars)subStars.innerText=selectedStars==="All"?(currentLang==='tr'?"Tüm Zorluklar":"All Difficulties"):(typeof selectedStars==='number'?"★".repeat(selectedStars):selectedStars);}
function togglePanel(type){const targetPanel=document.getElementById(`panel-${type}`);const arrow=document.getElementById("toggle-arrow");document.querySelectorAll('.nav-tab').forEach(tab=>tab.classList.remove('active-tab'));if(activeOpenedPanel===type){if(targetPanel)targetPanel.style.display="none";activeOpenedPanel=null;if(arrow)arrow.innerHTML=`<i class="fa-solid fa-chevron-down"></i>`}else{if(activeOpenedPanel){const currentOpened=document.getElementById(`panel-${activeOpenedPanel}`);if(currentOpened)currentOpened.style.display="none"}
if(targetPanel)targetPanel.style.display="block";activeOpenedPanel=type;lastActiveTab=type;if(arrow)arrow.innerHTML=`<i class="fa-solid fa-chevron-up"></i>`;const activeTabEl=document.getElementById(`tab-${type}`);if(activeTabEl)activeTabEl.classList.add('active-tab');}}
let selectedSubArea="All";function setArea(areaName){selectedArea=areaName;selectedSubArea="All";syncButtons("#grid-area",areaName);renderSubAreaBar(areaName);updateTabSubtitles();updateTable()}
function setSubArea(subAreaName){selectedSubArea=subAreaName;const subBtns=document.querySelectorAll("#grid-sub-area .filter-btn");subBtns.forEach(btn=>{btn.classList.remove("active");if(btn.getAttribute("data-sub")===subAreaName){btn.classList.add("active")}});updateTabSubtitles();updateTable()}
function renderSubAreaBar(parentArea){const wrapper=document.getElementById("sub-area-wrapper");const grid=document.getElementById("grid-sub-area");if(!wrapper||!grid)return;const subAreas=subAreaMap[parentArea]||[];if(parentArea==="All"||subAreas.length===0){wrapper.style.display="none";grid.innerHTML="";return}
let html=`
        <button class="filter-btn active" data-sub="All" onclick="setSubArea('All')">
            All ${parentArea} Zones
        </button>
    `;subAreas.forEach(sub=>{html+=`
            <button class="filter-btn" data-sub="${sub}" onclick="setSubArea('${sub}')">
                ${sub}
            </button>
        `});grid.innerHTML=html;wrapper.style.display="block"}
function setBait(baitName){selectedBait=baitName;updateTabSubtitles();syncButtons("#grid-bait",baitName);updateTable()}
function setStars(starCount){selectedStars=starCount;updateTabSubtitles();syncButtons("#grid-stars",starCount);updateTable()}
function syncButtons(gridSelector,activeValue){const buttons=document.querySelectorAll(`${gridSelector} .filter-btn`);buttons.forEach(btn=>{btn.classList.remove("active");const clickAttr=btn.getAttribute("onclick")||"";const stringMatch=clickAttr.match(/(?:setArea|setBait|setStars)\s*\(\s*(['"])(.*?)\1\s*\)/);if(stringMatch&&stringMatch[2].trim()===String(activeValue).trim()){btn.classList.add("active");return}
const numberMatch=clickAttr.match(/setStars\s*\(\s*(\d+)\s*\)/);if(numberMatch&&Number(numberMatch[1])===Number(activeValue)){btn.classList.add("active");return}
if(btn.dataset.area===String(activeValue)||btn.dataset.bait===String(activeValue)||btn.dataset.stars===String(activeValue)){btn.classList.add("active")}})}
function resetAllFilters(){selectedArea="All";selectedSubArea="All";selectedBait="All";selectedStars="All";if(searchInput)searchInput.value="";const wrapper=document.getElementById("sub-area-wrapper");const grid=document.getElementById("grid-sub-area");if(wrapper)wrapper.style.display="none";if(grid)grid.innerHTML="";syncButtons("#grid-area","All");syncButtons("#grid-bait","All");syncButtons("#grid-stars","All");if(activeOpenedPanel){const panel=document.getElementById(`panel-${activeOpenedPanel}`);if(panel)panel.style.display="none";activeOpenedPanel=null}
document.querySelectorAll('.nav-tab').forEach(tab=>tab.classList.remove('active-tab'));lastActiveTab="area";const arrow=document.getElementById("toggle-arrow");if(arrow)arrow.innerHTML=`<i class="fa-solid fa-chevron-down"></i>`;updateTabSubtitles();buildTableStructure();updateTable()}
function toggleCurrentPanel(){togglePanel(lastActiveTab)}
function handleImageLoad(imgObj){const placeholder=imgObj.nextElementSibling;if(placeholder)placeholder.style.display='none'}
function handleImageError(imgObj){imgObj.style.display='none';const placeholder=imgObj.nextElementSibling;if(placeholder)placeholder.style.display='block'}
function buildTableStructure(){const theadRow=document.querySelector(".fish-table thead tr");if(theadRow){theadRow.innerHTML=`
            <th style="width: 130px; text-align: center;">${langPack[currentLang].thImage}</th>
            <th style="width: 180px;">${langPack[currentLang].thFish}</th>
            <th>${langPack[currentLang].thArea}</th>
            <th>${langPack[currentLang].thBait}</th>
            <th>${langPack[currentLang].thSeason}</th>
            <th>${langPack[currentLang].thTime}</th>
            <th>${langPack[currentLang].thRecord}</th>
            <th>${langPack[currentLang].thPrice}</th>
        `}}
function appendMoreFish(){if(!tableBody||gosterilenBalikSayisi>=globalFiltrelenmisBaliklar.length)return;const sonrakiPaket=globalFiltrelenmisBaliklar.slice(gosterilenBalikSayisi,gosterilenBalikSayisi+SAYFA_BASINA_BALIK);let htmlChunk="";sonrakiPaket.forEach((fish,i)=>{const gerçekIndex=gosterilenBalikSayisi+i;const imageName=fish.name.toLowerCase().replace(/ /g,"-")+".png";const imagePath=`images/${imageName}`;const worldRecord=fish.record?fish.record:"-";const maxPrice=fish.price?fish.price:"-";const starsHtml=`<div class="stars-display">${"★".repeat(fish.stars)}</div>`;const areaText=Array.isArray(fish.area)?fish.area.join(",<br>"):(fish.area||"-");const baitText=Array.isArray(fish.bait)?fish.bait.join(",<br>"):(fish.bait||"-");const seasonText=fish.season?fish.season.replace(/, /g,',<br>'):'Always';const timeText=fish.time?fish.time.replace(/, /g,',<br>'):'Always';const imgBoxHtml=`
            <td style="text-align: center; vertical-align: middle; width: 130px;">
                <div style="width: 110px; height: 110px; border-radius: 8px; border: 1px solid #ddd; background-color: #ffffff; display: flex; align-items: center; justify-content: center; position: relative; margin: 0 auto; box-sizing: border-box; overflow: hidden;">
                    <img src="${imagePath}" alt="" style="max-width: 90%; max-height: 90%; object-fit: contain; display: block; margin: auto; z-index: 2;" onload="handleImageLoad(this)" onerror="handleImageError(this)">
                    <span class="img-placeholder" style="font-size: 24px; font-weight: bold; color: #0d5c75; z-index: 1; display: none; position: absolute;">?</span>
                </div>
            </td>
        `;htmlChunk+=`
            <tr id="fish-row-${gerçekIndex}">
                ${imgBoxHtml}
                <td style="vertical-align: middle; width: 180px; padding-left: 15px; text-align: left;">
                    <span class="fish-name" style="font-size: 18px;">${fish.name}</span>
                    ${starsHtml}
                </td>
                <td class="area-cell" style="vertical-align: middle;">${areaText}</td>
                <td class="bait-cell" style="vertical-align: middle;">${baitText}</td>
                <td style="vertical-align: middle;"><i class="fa-solid fa-calendar-days"></i> ${seasonText}</td>
                <td style="vertical-align: middle;"><i class="fa-regular fa-clock"></i> ${timeText}</td>
                <td style="vertical-align: middle; font-weight: 600; color: #2c3e50;"><i class="fa-solid fa-trophy" style="color:#d4af37;"></i> ${worldRecord}</td>
                <td style="vertical-align: middle; font-weight: 600; color: #27ae60;"><i class="fa-solid fa-money-bill-wave"></i> ${maxPrice}</td>
            </tr>`});tableBody.innerHTML+=htmlChunk;gosterilenBalikSayisi+=sonrakiPaket.length}
function updateTable(){if(!window.fishData||!tableBody)return;const searchValue=searchInput?searchInput.value.trim().toLowerCase():"";globalFiltrelenmisBaliklar=window.fishData.filter(fish=>{const matchesArea=(function(){if(selectedArea==="All")return!0;if(!fish.area)return!1;const fishAreas=Array.isArray(fish.area)?fish.area:[fish.area];if(typeof selectedSubArea!=="undefined"&&selectedSubArea!=="All"){return fishAreas.some(a=>a.toLowerCase().trim()===selectedSubArea.toLowerCase().trim())}
return fishAreas.some(a=>{const areaName=a.toLowerCase().trim();const targetArea=selectedArea.toLowerCase().trim();return areaName===targetArea||areaName.startsWith(targetArea+" (")})})();const matchesBait=selectedBait==="All"||(Array.isArray(fish.bait)&&fish.bait.some(b=>b.toLowerCase().trim()===selectedBait.toLowerCase().trim()));const matchesStars=selectedStars==="All"||fish.stars===Number(selectedStars);const matchesSearch=fish.name.toLowerCase().includes(searchValue);return matchesArea&&matchesBait&&matchesStars&&matchesSearch});const matchCount=globalFiltrelenmisBaliklar.length;const countEl=document.getElementById("filteredCount");if(countEl)countEl.innerText=matchCount;tableBody.innerHTML="";gosterilenBalikSayisi=0;if(matchCount===0){tableBody.innerHTML=`<tr id="no-fish-alert-row"><td colspan="8" style="text-align:center; color:#999; padding: 20px;">${langPack[currentLang].noFish}</td></tr>`;return}
appendMoreFish()}
document.addEventListener("DOMContentLoaded",()=>{if('scrollRestoration' in history){history.scrollRestoration='manual'}
window.scrollTo(0,0);if(searchInput){searchInput.value="";searchInput.addEventListener("input",()=>{clearTimeout(searchTimeout);searchTimeout=setTimeout(()=>{updateTable()},100)})}
window.addEventListener("scroll",()=>{if((window.innerHeight+window.scrollY)>=document.documentElement.scrollHeight-150){appendMoreFish()}});setTimeout(()=>{const intro=document.getElementById("fairnight-intro");if(intro){intro.style.opacity="0";intro.style.visibility="hidden"}},2500);if(searchInput)searchInput.placeholder=langPack.en.searchPlaceholder;const flagEl=document.getElementById("lang-flag");if(flagEl)flagEl.innerText="🇹🇷";if(window.fishData){const totalEl=document.getElementById("totalCount");if(totalEl)totalEl.innerText=window.fishData.length}
updateTabSubtitles();buildTableStructure();updateTable()});function toggleTheme(){const body=document.body;const icon=document.getElementById("theme-icon");body.classList.toggle("dark-mode");const isDark=body.classList.contains("dark-mode");if(icon){icon.className=isDark?"fa-solid fa-sun":"fa-solid fa-moon";icon.style.color=isDark?"#f59e0b":"#0d5c75"}
localStorage.setItem("theme",isDark?"dark":"light")}
document.addEventListener("DOMContentLoaded",()=>{const savedTheme=localStorage.getItem("theme");const icon=document.getElementById("theme-icon");if(savedTheme==="dark"){document.body.classList.add("dark-mode");if(icon){icon.className="fa-solid fa-sun";icon.style.color="#f59e0b"}}else{document.body.classList.remove("dark-mode");if(icon){icon.className="fa-solid fa-moon";icon.style.color="#0d5c75"}}})